-- SQL Commands to Insert Students
-- Password: petra123 (hashed with bcrypt)
-- Center ID: 1 (Cotha)
-- Email format: firstname.lastname@student.cotha.id

-- Insert Users
INSERT INTO `users` (`name`, `email`, `password`, `center_id`, `gender`, `created_at`, `updated_at`) VALUES
('Andrea Wynne Hartanto', 'andrea.wynne@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Cornelius jasver dante wijaya', 'cornelius.jasver@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Dominique valencia yulianto', 'dominique.valencia@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Jade Louie', 'jade.louie@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jayden Patrick Tirto Budiono', 'jayden.patrick@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jill Angelia Tenardi', 'jill.angelia@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Matthew Gavriel Ko', 'matthew.gavriel@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Megan Faith Tirto Budiono', 'megan.faith@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('RM Revandra Putra Suryadiningrat', 'rm.revandra@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Steve Wayne Hartanto', 'steve.wayne@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Alexander Ethan Suwarno', 'alexander.ethan@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Alicia Tedjosaputro', 'alicia.tedjosaputro@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Ben Xavier Wiguno', 'ben.xavier@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Charla Valencia Linando', 'charla.valencia@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('George Lie', 'george.lie@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Gifford Luc Halim', 'gifford.luc@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jason Fritz Hartono', 'jason.fritz@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jericho Winson Kweejaya', 'jericho.winson@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jonathan Myers Tanaya', 'jonathan.myers@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Made Fairel Paramaditya Maheswara', 'made.fairel@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Mikhael Dante Seraphin', 'mikhael.dante@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Nyoman Aditya Natha Maheswara', 'nyoman.aditya@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Samantha Cilya Josephine', 'samantha.cilya@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Vhionix Kayra Hartono', 'vhionix.kayra@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('William Tedjosaputro', 'william.tedjosaputro@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Alden Hanjaya Tios', 'alden.hanjaya@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Christyan Amadeus Sulistya', 'christyan.amadeus@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('FELIX ALEXANDER WIDIYANTO', 'felix.alexander@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('JOEL GAVRIEL ERICSON', 'joel.gavriel@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Joel Maximillian Lumunon', 'joel.maximillian@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Joquina Quenelle Subroto', 'joquina.quenelle@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('JOSES SHAWN ERICSON', 'joses.shawn@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Rafael lucius augustian toly', 'rafael.lucius@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Savierro Hartanto', 'savierro.hartanto@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Sebastian Hartanto', 'sebastian.hartanto@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('ALDRICH NIKOLAJ DARMAWAN', 'aldrich.nikolaj@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('AURORA ANGELA CHRISTIANI BR SIBUEA', 'aurora.angela@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Cicilia Ratih Widya', 'cicilia.ratih@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('DAVE JEREMIAH', 'dave.jeremiah@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Dearlynn Shea Quinn Gunawan', 'dearlynn.shea@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('ELLAYNE MICHELLE JOANNA', 'ellayne.michelle@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Fidelia Gizelle', 'fidelia.gizelle@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Giovanna Nathalie', 'giovanna.nathalie@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('JAYDEN ALDRIC', 'jayden.aldric@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Laureen Abigail Soenarto', 'laureen.abigail@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Nicholas Aaron Simanjuntak', 'nicholas.aaron@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Oswell Aaron P', 'oswell.aaron@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('William Harrison Wijaya', 'william.harrison@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Valerie Nathaniela', 'valerie.nathaniela@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Starry Jasmine Graciella Tarigan', 'starry.jasmine@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Alexander Christopher Tanur', 'alexander.christopher@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Cathleen chloe kurniawan', 'cathleen.chloe@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Clairine Felisa Octaviano', 'clairine.felisa@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Clement Tjandrawinata', 'clement.tjandrawinata@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Dewa Ketut Radika Daniswara Darmawan', 'dewa.ketut@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Dewa Nyoman Adrian Narendra Darmawan', 'dewa.nyoman@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Ethan Alvaro Halim', 'ethan.alvaro@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Gevariel Bryan Hunsam', 'gevariel.bryan@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Gracella Alicia Novadianto', 'gracella.alicia@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('GRACIA ALLELUIA RAHAYU', 'gracia.alleluia@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Harvey Austin Santoso', 'harvey.austin@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jayden Angelo Soegiarto', 'jayden.angelo@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Jeremy hans santoso', 'jeremy.hans@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Joshua Elknighten Kenji Edward Giroth', 'joshua.elknighten@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Kenichi Jefferson Tjeang', 'kenichi.jefferson@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('leticia fedora', 'leticia.fedora@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Liem Botti Hendrawan', 'liem.botti@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Matthew Chu', 'matthew.chu@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Praiselle Jemima Purnomo', 'praiselle.jemima@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Rendra Julian Tanara', 'rendra.julian@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Rodrigo Austin Gunarso', 'rodrigo.austin@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Sean Laurent Wijaya', 'sean.laurent@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Shane Edward Sucahyono', 'shane.edward@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Valerie Emmanuel Tantoro', 'valerie.emmanuel@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('William Keitaro Thenaryo', 'william.keitaro@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Callysta velove sutjonong', 'callysta.velove@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Dave Alpha Riyadi', 'dave.alpha@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Joyceline Shalom Halim', 'joyceline.shalom@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Perempuan', NOW(), NOW()),
('Prince Daniel Igwe', 'prince.daniel@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Richard Vincentius Mintardja', 'richard.vincentius@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW()),
('Scheivo mark santoso', 'scheivo.mark@student.cotha.id', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Laki-laki', NOW(), NOW());

-- Insert Students (using the user IDs from the above insert)
-- Note: Replace the user_id values with the actual IDs generated from the users insert above
-- You'll need to run this after the users insert and get the generated IDs

INSERT INTO `students` (`user_id`, `school`, `status`, `created_at`, `updated_at`) VALUES
((SELECT id FROM users WHERE email = 'andrea.wynne@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'cornelius.jasver@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dominique.valencia@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jade.louie@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jayden.patrick@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jill.angelia@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'matthew.gavriel@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'megan.faith@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'rm.revandra@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'steve.wayne@student.cotha.id'), 'SD Kristen Petra 1', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'alexander.ethan@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'alicia.tedjosaputro@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'ben.xavier@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'charla.valencia@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'george.lie@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'gifford.luc@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jason.fritz@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jericho.winson@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jonathan.myers@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'made.fairel@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'mikhael.dante@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'nyoman.aditya@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'samantha.cilya@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'vhionix.kayra@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'william.tedjosaputro@student.cotha.id'), 'SD Kristen Petra 10', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'alden.hanjaya@student.cotha.id'), 'SD Kristen Petra 11', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'christyan.amadeus@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'felix.alexander@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joel.gavriel@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joel.maximillian@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joquina.quenelle@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joses.shawn@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'rafael.lucius@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'savierro.hartanto@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'sebastian.hartanto@student.cotha.id'), 'SD Kristen Petra 12', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'aldrich.nikolaj@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'aurora.angela@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'cicilia.ratih@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dave.jeremiah@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dearlynn.shea@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'ellayne.michelle@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'fidelia.gizelle@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'giovanna.nathalie@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jayden.aldric@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'laureen.abigail@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'nicholas.aaron@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'oswell.aaron@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'william.harrison@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'valerie.nathaniela@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'starry.jasmine@student.cotha.id'), 'SD Kristen Petra 13', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'alexander.christopher@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'cathleen.chloe@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'clairine.felisa@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'clement.tjandrawinata@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dewa.ketut@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dewa.nyoman@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'ethan.alvaro@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'gevariel.bryan@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'gracella.alicia@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'gracia.alleluia@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'harvey.austin@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jayden.angelo@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'jeremy.hans@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joshua.elknighten@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'kenichi.jefferson@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'leticia.fedora@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'liem.botti@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'matthew.chu@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'praiselle.jemima@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'rendra.julian@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'rodrigo.austin@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'sean.laurent@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'shane.edward@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'valerie.emmanuel@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'william.keitaro@student.cotha.id'), 'SD Kristen Petra 5', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'callysta.velove@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'dave.alpha@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'joyceline.shalom@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'prince.daniel@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'richard.vincentius@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()),
((SELECT id FROM users WHERE email = 'scheivo.mark@student.cotha.id'), 'SD Kristen Petra 7', 'Active', NOW(), NOW()); 